[workspace]
resolver = "2"
members = [ "destitute-code", "destitute-macro" , "destitute-usage"]

[workspace.dependencies]
destitute-macro = { path = "./destitute-macro" }
destitute-code = { path = "./destitute-code" }
